main: main.o C4Col.o C4Board.o
        g++ -o main main.o C4Col.o C4Board.o
main.o: main.cpp
        g++ -c main.cpp
C4Col.o: C4Col.cpp
        g++ -c C4Col.cpp
C4Board.o: C4Board.cpp
        g++ -c C4Board.cpp
clean:
        rm *.o main


