# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1424639946);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1424373044);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1424639586);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1424639826);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1424639706);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150106055458");
user_pref("browser.slowStartup.averageTime", 1177);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150106055458");
user_pref("browser.startup.homepage_override.mstone", "31.4.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1424639527162");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1424639527712");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1424725927712");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1412622005886");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1412623926892");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1409598839280");
user_pref("datareporting.sessions.current.activeTicks", 20);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 928);
user_pref("datareporting.sessions.current.main", 265);
user_pref("datareporting.sessions.current.sessionRestored", 984);
user_pref("datareporting.sessions.current.startTime", "1424639465853");
user_pref("datareporting.sessions.current.totalTime", 572);
user_pref("datareporting.sessions.currentIndex", 23);
user_pref("datareporting.sessions.prunedIndex", 22);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 16);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1423343384000,\"rdfTime\":1420542644000}}}]");
user_pref("extensions.lastAppVersion", "31.4.0");
user_pref("extensions.lastPlatformVersion", "31.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20150106055458");
user_pref("gecko.mstone", "31.4.0");
user_pref("idle.lastDailyNotification", 1424639704);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1424639527);
user_pref("places.history.expiration.transient_current_max_pages", 98954);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1424372631);
user_pref("toolkit.startup.last_success", 1424639466);
user_pref("toolkit.telemetry.previousBuildID", "20150106055458");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1416089083);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
